# .github/workflows/azure-deploy.yml

name: Build and Deploy ASP.NET Core App to Azure Web App - quizify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # Specify your .NET version

      # Step 3: Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore ./cms24_delta_umbraco/cms24_delta_umbraco.csproj

      # Step 4: Build the project
      - name: Build Project
        run: dotnet build ./cms24_delta_umbraco/cms24_delta_umbraco.csproj --configuration Release --no-restore

      # Step 5: Publish the project
      - name: Publish Project
        run: dotnet publish ./cms24_delta_umbraco/cms24_delta_umbraco.csproj --configuration Release --output ./publish

      # Step 6: Zip the publish folder
      - name: Zip Publish Folder
        run: Compress-Archive -Path ./publish/* -DestinationPath ./publish.zip

      # Step 7: Upload the zipped artifact for deployment
      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: publish-artifact
          path: ./publish.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      # Step 1: Download the artifact from the build job
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: publish-artifact
          path: ./publish

      # Step 2: Login to Azure using service principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6BF553A983D14E4ABAD7C3701E376364 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_36863C1413D24FDFA150E2075FE361DC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FD501A0F1F6F40209B1F6BF7CC872F35 }}

      # Step 3: Deploy the zipped publish folder to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'quizify' # Your Azure App Service name
          slot-name: 'Production' # Change if using deployment slots
          package: ./publish.zip
